apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orders-db-temp-pvc
  namespace: sock-shop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ibmc-vpc-block-10iops-tier