apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: mac-mutate
namespace: mac-mutate

resources:
  - project.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - webhook_configuration.yaml

sortOptions:
  order: fifo
