apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
        app.kubernetes.io/component: frontend
    spec:
      metadata:
        name: frontend
        labels:
          app: frontend
          app.kubernetes.io/component: frontend
        annotations: 
          "descheduler.alpha.kubernetes.io/evict": "true"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - backend
              topologyKey: kubernetes.io/hostname
      containers:
      - name: frontend
        image: registry.access.redhat.com/ubi8/pause:latest
        imagePullPolicy: IfNotPresent
      restartPolicy: Always