apiVersion: apps/v1
kind: Deployment
metadata:
  name: lifetime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lifetime
  template:
    metadata:
      name: lifetime
      labels:
        app: lifetime
    spec:
      containers:
      - name: lifetime
        image: registry.access.redhat.com/ubi8/pause:latest
        imagePullPolicy: IfNotPresent
      restartPolicy: Always