apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbalanced
spec:
  replicas: 10
  selector:
    matchLabels:
      app: unbalanced
  template:
    metadata:
      name: unbalanced
      labels:
        app: unbalanced
    spec:
      containers:
      - name: unbalanced
        image: registry.access.redhat.com/ubi8/pause:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      restartPolicy: Always