apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: foobar-violator-0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
        test: topology-spread-soft-constrainta
      namespace: test
    spec:
#      nodeSelector:
#        topology.kubernetes.io/zone: a
      containers:
      - image: registry.access.redhat.com/ubi8/pause:latest
        imagePullPolicy: IfNotPresent
        name: foo
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000760000
          seccompProfile:
            type: RuntimeDefault
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: foo
        maxSkew: 1
        topologyKey: skewtest
        whenUnsatisfiable: ScheduleAnyway