apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ua
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ua
  template:
    metadata:
      name: ua
      labels:
        app: ua
    spec:
      containers:
      - name: ua
        image: registry.access.redhat.com/ubi8/pause:latest
        imagePullPolicy: IfNotPresent
      restartPolicy: Always