apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: unbalanced
spec:
  replicas: 2
  selector:
    matchLabels:
      app: unbalanced
  template:
    metadata:
      name: unbalanced
      labels:
        app: unbalanced
    spec:
      containers:
      - name: unbalanced
        image: registry.access.redhat.com/ubi8/pause:latest
        imagePullPolicy: IfNotPresent
      restartPolicy: Always