apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-storage
  template:
    metadata:
      name: local-storage
      labels:
        app: local-storage
    spec:
      containers:
      - name: local-storage
        image: registry.access.redhat.com/ubi8/pause:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: "/cache" 
            name: cache-volume
      volumes:
      - name: cache-volume
        emptyDir: {}
      restartPolicy: Always