apiVersion: operator.openshift.io/v1
kind: KubeDescheduler
metadata:
  name: cluster
  namespace: openshift-kube-descheduler-operator
spec:
  logLevel: Normal
  mode: Automatic
  operatorLogLevel: Normal
  deschedulingIntervalSeconds: 60
  profileCustomizations:
    podLifetime: 1m0s
    namespaces:
      excluded:
        - 'nfs-provisioner'
      included:
        - 'test'
  profiles:
    - LifecycleAndUtilization
    - EvictPodsWithPVC
  managementState: Managed
