---
apiVersion: v1
kind: Service
metadata:
  name: intel
  labels:
    name: intel
  namespace: net-debug
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 8080
  selector:
    name: intel
